[package]
name = "genanki-rs-rev"
version = "0.3.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/Whth/genanki-rs-rev"
description = "Crate to create decks for the open source flashcard platform Anki. Based on Python library genanki"


[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.17"
blake3 = { version = "1.8.2", default-features = false, features = ["pure"] }
hex = "0.4.3"
fancy-regex = "0.17.0"
ramhorns = "1.0.1"
rusqlite = { version = "0.40.1", default-features = false, features = ["ffi-sqlite-wasm-rs", "serialize"] }
zip = { version = "8", optional = true,default-features = false, features = [
    "deflate",
] }
anyhow = "1.0.100"
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
[dev-dependencies]
tempfile = "3.24.0"

[features]
default = ["export"]
export = ["zip"]
