[package]
name = "genanki-rs-rev"
version = "0.3.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/Whth/genanki-rs-rev"
description = "Crate to create decks for the open source flashcard platform Anki. Based on Python library genanki"


[dependencies]
# Core dependencies
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = {version="1.0.148",default-features=false,features=["std"]}
thiserror = {version="2.0.17",default-features=false}
blake3 = { version = "1.8.2", default-features = false, features = ["pure"] }
hex = {version="0.4.3",default-features=false,features=["std"]}
ramhorns = {version="1.0.1",default-features=false}
rusqlite = { version = "0.40.1", default-features = false, features = ["ffi-sqlite-wasm-rs", "serialize"] }
zip = { version = "8", optional = true,default-features = false,features = ["deflate"]}
anyhow = {version="1.0.100",default-features=false}
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fancy-regex = {version="0.17.0"}
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = {version="0.3",default-features=false}
[dev-dependencies]
tempfile = {version="3.24.0",default-features=false}

[features]
default = ["export"]
export = ["zip"]
